services:
  - type: web
    name: sitehot
    env: node
    plan: starter  # plano pago
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    healthCheckPath: /health-basic
    healthCheckTimeoutSeconds: 120
    envVars:
      - key: PORT
        value: 10000
