ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_source TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_medium TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_campaign TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_term TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_content TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS event_time INTEGER;
UPDATE tokens SET event_time = EXTRACT(EPOCH FROM criado_em)::INTEGER WHERE event_time IS NULL;
