ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_source TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_medium TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_campaign TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_term TEXT;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS utm_content TEXT;
